[providers.deepseek]
type = "native"
provider = "deepseek"
name = "Deepseek"

[[providers.deepseek.models]]
name = "deepseek-flash"
model = "deepseek-flash"
temperature = 0.7
max_tokens = 8000
reasoning_effort = "xhigh"

[providers.llamacpp]
type = "openai"
name = "Llamacpp Local"
base_url = "<WEFTIC_LLAMACPP_HOST>"
api_key = "<WEFTIC_LLAMACPP_HOST_API_KEY>"

[[providers.llamacpp.models]]
name = "bonsai-27B"
model = "Bonsai-27B-PQ2_0"

[route]
# main = "deepseek/deepseek-flash"
main = "llamacpp/bonsai-27B"
